//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda_acceso_datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int CompraID { get; set; }
        public string CodigoCompra { get; set; }
        public string AsientosAsignados { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Salas Salas { get; set; }
    }
}
