//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda_acceso_datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosProveedores
    {
        public int PedidoID { get; set; }
        public string EstadoPedido { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
